// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcC1FFUugdWSbm-wLYUxA5-0XUKhmFJOM',
    appId: '1:565546255503:ios:c608e377d761d373f61cfa',
    messagingSenderId: '565546255503',
    projectId: 'app-fmovil',
    databaseURL:
        'https://app-fmovil-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fmovil.appspot.com',
    iosBundleId: 'com.movilfinalisimo.finalmovil1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcC1FFUugdWSbm-wLYUxA5-0XUKhmFJOM',
    appId: '1:565546255503:ios:c608e377d761d373f61cfa',
    messagingSenderId: '565546255503',
    projectId: 'app-fmovil',
    databaseURL:
        'https://app-fmovil-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fmovil.appspot.com',
    iosBundleId: 'com.movilfinalisimo.finalmovil1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5iwkyFgq9ge34KOxxgOc-Ei8X6kcpcw',
    appId: '1:565546255503:web:1e451c758b7407a7f61cfa',
    messagingSenderId: '565546255503',
    projectId: 'app-fmovil',
    authDomain: 'app-fmovil.firebaseapp.com',
    databaseURL:
        'https://app-fmovil-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fmovil.appspot.com',
    measurementId: 'G-74ZB91Y2FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOsgZzToPigTaD23Rfp2yz0ptS82EX2NI',
    appId: '1:565546255503:android:a727b642373625f7f61cfa',
    messagingSenderId: '565546255503',
    projectId: 'app-fmovil',
    databaseURL:
        'https://app-fmovil-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fmovil.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW5iwkyFgq9ge34KOxxgOc-Ei8X6kcpcw',
    appId: '1:565546255503:web:24c936ec114c08a1f61cfa',
    messagingSenderId: '565546255503',
    projectId: 'app-fmovil',
    authDomain: 'app-fmovil.firebaseapp.com',
    databaseURL:
        'https://app-fmovil-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-fmovil.appspot.com',
    measurementId: 'G-6N34KD9CRK',
  );
}
